### ISSUE TITLE
select_features.py StopIteration

### ISSUE THREAD

**Issue by XingLiu93** [HarshTrivedi/feature-selection-for-learning-to-rank#1]
After running successfully first program, second program running met some problems. it says:
```
About to start with balancing factor: 0.1
starting method: gas
Traceback (most recent call last):
  File "2.select_features.py", line 22, in <module>
    ranked_features = gas.select( os.path.join(root_directory, "query_wise_rankings"), os.path.join(root_directory, "ranking_scores"), total_number_of_features, balancing_factor)
  File "lib/gas.py", line 33, in select
    fscores = upd_rel_score(max_feature,fscores, query_wise_rankings_directory, feature_numbers, query_ids,balancing_factor)
  File "lib/gas.py", line 67, in upd_rel_score
    line = fi.next().strip()
StopIteration

```
I create the trainingset and testset and qrels files as the example shows. But I do not know why this happens. Do you have any ideas?
Thanks

**Comment by HarshTrivedi** [comment]
You need to have at least 10 documents in your training set. In qrels, each query needs to have a ranking for at least 10 documents. I believe that your training set you doesn't have enough documents. If you want to check if this is the problem, you can change `range(10)` to whatever is your datasets lower bound in each of `gas.py`, `mmr.py`, `mpt.py`, `msd.py`.

**Comment by XingLiu93** [comment]
Hi Harsh, thanks for replying. I checked my file, each query has more than 10 documents. The error still exists. Is there some limitation for training data size? My training data has 70,000 rows. When I tried with 1000 rows, it works. 
This is my training data example.
```
1 qid:25 1:5.02595809938e-05 2:1.70661912109e-05 3:0.000204425709865 4:0.000547743199074 5:0.098552078468 6:0.290233837689 7:1 8:1 9:0.00518134715026 10:0.00346020761246 11:0.0865051903114 12:1 13:2.10926255874e-05 14:1.47607166704e-05 15:0.788933925096 16:0.0794128716598 17:4.95318616987e-06 18:1 19:0.543252595156 20:0.877481771878 21:0.800279574568 22:0.0922199865862 23:1218391.04434 24:0.0 25:3128232.2631 26:9.15184687433e-06 27:1527001.95365 28:8.6612410186 #docid = 37556
2 qid:25 1:5.02595809938e-05 2:9.81247307585e-06 3:0.000122968453594 4:0.000547743199074 5:0.0583839327417 6:0.299043062201 7:1 8:1 9:0.0113636363636 10:0.00346020761246 11:0.131487889273 12:1 13:4.16550906049e-05 14:2.4418791389e-05 15:0.753663720965 16:0.0513557929334 17:2.93435199637e-06 18:1 19:0.565743944637 20:0.838725860071 21:0.769786505146 22:0.0642510272693 23:743706.092967 24:0.0 25:2051871.91724 26:0.0 27:1100912.11593 28:8.69114166743 #docid = 29113700
3 qid:25 1:5.02595809938e-05 2:2.65265420472e-05 3:0.000306046039045 4:0.000547743199074 5:0.0172816440915 6:0.0327433628319 7:0 8:0 9:0 10:0 11:0.0173010380623 12:0.0111607142857 13:8.38589816554e-06 14:6.78139126182e-06 15:0.614883751654 16:0.0114409400124 17:8.68568190925e-07 18:0 19:0.014230876174 20:0.603517841121 21:0.619506955989 22:0.0125195618153 23:24103.1357013 24:0.0 25:5264.22565459 26:0.999999999441 27:27354.2588184 28:6.47925436359 #docid = 1845
...
11 qid:25 1:5.02595809938e-05 2:2.30053196515e-06 3:3.21668868843e-05 4:0.000547743199074 5:0.0200840728631 6:0.438775510204 7:1 8:1 9:0.0454545454545 10:0.00346020761246 11:0.0484429065744 12:1 13:0.000107045705094 14:4.08652186275e-05 15:0.698989620466 16:0.0195810564663 17:1.00941708675e-06 18:1 19:0.524221453287 20:0.742992493024 21:0.708675494004 22:0.0231309376291 23:375379.041841 24:0.0 25:328299.58383 26:0.0 27:504313.481534 28:9.07454199968 #docid = 242189

```

**Comment by HarshTrivedi** [comment]
Hi Hailey,
It doesn't have any restriction on the maximum number of examples. In the `trainingset.txt` that I have provided as a sample, it also has 9K+ records. I still believe that the problem is because of not having enough (10) documents for some query. One thing you can check is go to `query_wise_rankings` directory after running the preprocessing script. And check that each of those files has > 10 lines: `wc -l *` and sort the first column and see what is a minimum number of lines. fXqY means feature number X and query Y. You can also print a log around the error in `gas.py` and see which feature number and query it is causing the problem.

**Comment by XingLiu93** [comment]
Thanks a lot. You are right. I found one query with only 2 documents. :)

**Comment by HarshTrivedi** [comment]
Cool, No problem : )
